

/************ Update: Schemas ***************/

/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE public.tb_adm_permissions_idnpermission_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_adm_permissions_idnpermission_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_adm_roles_idnrole_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_adm_roles_idnrole_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_adm_rolesxpermissions_idnrolexperm_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_adm_rolesxpermissions_idnrolexperm_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_adm_users_idnuser_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_adm_users_idnuser_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_author_idnauthor_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_author_idnauthor_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_authorxproject_idnauthorxprj_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_authorxproject_idnauthorxprj_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_documents_idndocument_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_documents_idndocument_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_projects_idnprj_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_projects_idnprj_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_projects_labels_idprjlabel_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_projects_labels_idprjlabel_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_projects_types_idnprjtype_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_projects_types_idnprjtype_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_projectxlabel_idnprjxlabel_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_projectxlabel_idnprjxlabel_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.tb_prj_typesxproject_idntypesxprj_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tb_prj_typesxproject_idntypesxprj_seq IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: public.tb_adm_permissions ************************/

/* Build Table Structure */
CREATE TABLE public.tb_adm_permissions
(
	idnpermission INTEGER DEFAULT nextval('public.tb_adm_permissions_idnpermission_seq'::regclass) NOT NULL,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(200) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_adm_permissions ADD CONSTRAINT pktb_adm_permissions
	PRIMARY KEY (idnpermission);

/* Add Comments */
COMMENT ON TABLE public.tb_adm_permissions IS 'tb_adm_permissions: Tabla para indicar los permisos de cada rol';


/******************** Rebuild Table: public.tb_adm_roles ************************
Reasons:
Column: idnrole
	Data type changed of a column used in a foreign key
	Server Column: idnrole, DT=BigInt, L=, COM=, N=false, AN=false, DF=, SC=, SI=true, EN=, ARR=false.
	Design Column: idnrole, DT=Integer, L=, COM=, N=false, AN=true, DF=, SC=, SI=true, EN=, ARR=false.
*****************************************************************************/


/* Build Table Structure */
CREATE TABLE public.tb_adm_roles
(
	idnrole INTEGER DEFAULT nextval('public.tb_adm_roles_idnrole_seq'::regclass) NOT NULL,
	namerole VARCHAR(50) NOT NULL,
	description VARCHAR(200) NOT NULL
);


/* Add Primary Key */
ALTER TABLE public.tb_adm_roles ADD CONSTRAINT pktb_adm_roles
	PRIMARY KEY (idnrole);

/* Add Comments */
COMMENT ON TABLE public.tb_adm_roles IS 'tb_adm_roles: Tabla para indicar los roles que desempeñan los usuarios dentro del sistema';


/******************** Rebuild Table: public.tb_adm_rolesxpermissions ************************
Reasons:
Column: idnrole
	Data type changed of a column used in a foreign key
	Server Column: idnrole, DT=BigInt, L=, COM=, N=false, AN=false, DF=, SC=, SI=true, EN=, ARR=false.
	Design Column: idnrole, DT=Integer, L=, COM=, N=false, AN=false, DF=, SC=, SI=true, EN=, ARR=false.
*****************************************************************************/

/* Build Table Structure */
CREATE TABLE public.tb_adm_rolesxpermissions
(
	idnrolexperm INTEGER DEFAULT nextval('public.tb_adm_rolesxpermissions_idnrolexperm_seq'::regclass) NOT NULL,
	idnpermission INTEGER NOT NULL,
	idnrole INTEGER NOT NULL
);


/* Add Primary Key */
ALTER TABLE public.tb_adm_rolesxpermissions ADD CONSTRAINT pktb_adm_rolesxpermissions
	PRIMARY KEY (idnrolexperm);

/* Add Comments */
COMMENT ON TABLE public.tb_adm_rolesxpermissions IS 'tb_adm_rolesxpermissions: Table for relatinshio table tb_adm_roles between tb_adm_permissions';


/******************** Add Table: public.tb_adm_users ************************/

/* Build Table Structure */
CREATE TABLE public.tb_adm_users
(
	idnuser INTEGER DEFAULT nextval('public.tb_adm_users_idnuser_seq'::regclass) NOT NULL,
	name VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	nameuser VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	idnrole INTEGER NOT NULL,
	email VARCHAR(200) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_adm_users ADD CONSTRAINT pktb_adm_users
	PRIMARY KEY (idnuser);

/* Add Comments */
COMMENT ON TABLE public.tb_adm_users IS 'tb_adm_users: Tabla encargada de almacenar información de los usuarios y sus campos necesarios para relacionar el usuario con el rol que desempeña dentro del sistema';


/******************** Add Table: public.tb_prj_author ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_author
(
	idnauthor INTEGER DEFAULT nextval('public.tb_prj_author_idnauthor_seq'::regclass) NOT NULL,
	name VARCHAR(50) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_author ADD CONSTRAINT pktb_prj_author
	PRIMARY KEY (idnauthor);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_author IS 'tb_prj_author:Table for save the author';


/******************** Add Table: public.tb_prj_authorxproject ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_authorxproject
(
	idnauthorxprj INTEGER DEFAULT nextval('public.tb_prj_authorxproject_idnauthorxprj_seq'::regclass) NOT NULL,
	idnprj INTEGER NOT NULL,
	idnauthor INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_authorxproject ADD CONSTRAINT pktb_prj_authorxproject
	PRIMARY KEY (idnauthorxprj);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_authorxproject IS 'tb_prj_authorxproject';


/******************** Add Table: public.tb_prj_documents ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_documents
(
	idndocument INTEGER DEFAULT nextval('public.tb_prj_documents_idndocument_seq'::regclass) NOT NULL,
	shortname VARCHAR(20) NOT NULL,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(200) NOT NULL,
	creationdate DATE NOT NULL,
	idnprj INTEGER NOT NULL,
	urlfile VARCHAR(200) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_documents ADD CONSTRAINT pktb_prj_documents
	PRIMARY KEY (idndocument);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_documents IS 'tb_prj_documents: Table for save documents';


/******************** Add Table: public.tb_prj_projects ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_projects
(
	shortname VARCHAR(20) NOT NULL,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(200) NOT NULL,
	creationdate DATE NOT NULL,
	idnprj INTEGER DEFAULT nextval('public.tb_prj_projects_idnprj_seq'::regclass) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_projects ADD CONSTRAINT pktb_prj_projects
	PRIMARY KEY (idnprj);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_projects IS 'tb_prj_projects: Table for save the projects';


/******************** Add Table: public.tb_prj_projects_labels ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_projects_labels
(
	idprjlabel INTEGER DEFAULT nextval('public.tb_prj_projects_labels_idprjlabel_seq'::regclass) NOT NULL,
	name VARCHAR(50) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_projects_labels ADD CONSTRAINT pktb_prj_projects_labels
	PRIMARY KEY (idprjlabel);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_projects_labels IS 'tb_prj_projects_labels: table for labels';


/******************** Add Table: public.tb_prj_projects_types ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_projects_types
(
	idnprjtype INTEGER DEFAULT nextval('public.tb_prj_projects_types_idnprjtype_seq'::regclass) NOT NULL,
	name VARCHAR(50) NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_projects_types ADD CONSTRAINT pktb_prj_projects_types
	PRIMARY KEY (idnprjtype);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_projects_types IS 'tb_prj_projects_types: Table for save projects types';


/******************** Add Table: public.tb_prj_projectxlabel ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_projectxlabel
(
	idnprjxlabel INTEGER DEFAULT nextval('public.tb_prj_projectxlabel_idnprjxlabel_seq'::regclass) NOT NULL,
	idprjlabel INTEGER NOT NULL,
	idnprj INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_projectxlabel ADD CONSTRAINT pktb_prj_projectxlabel
	PRIMARY KEY (idnprjxlabel);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_projectxlabel IS 'tb_prj_rolsxpermissions: Table for relation many and many the tables tb_prj_projects and tb_prj_projects_labels';


/******************** Add Table: public.tb_prj_typesxproject ************************/

/* Build Table Structure */
CREATE TABLE public.tb_prj_typesxproject
(
	idntypesxprj INTEGER DEFAULT nextval('public.tb_prj_typesxproject_idntypesxprj_seq'::regclass) NOT NULL,
	idnprj INTEGER NOT NULL,
	idnprjtype INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.tb_prj_typesxproject ADD CONSTRAINT pktb_prj_typesxproject
	PRIMARY KEY (idntypesxprj);

/* Add Comments */
COMMENT ON TABLE public.tb_prj_typesxproject IS 'tb_prj_typesxproject: Table for relation between table tb_prj_projects and tb_prj_typesprojects';



/************ Remove: Sequences ***************/




/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_tb_adm_rolesxpermissions_tb_adm_permissions */
ALTER TABLE public.tb_adm_rolesxpermissions ADD CONSTRAINT fk_tb_adm_rolesxpermissions_tb_adm_permissions
	FOREIGN KEY (idnpermission) REFERENCES public.tb_adm_permissions (idnpermission)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_adm_rolesxpermissions_tb_adm_roles */
ALTER TABLE public.tb_adm_rolesxpermissions ADD CONSTRAINT fk_tb_adm_rolesxpermissions_tb_adm_roles
	FOREIGN KEY (idnrole) REFERENCES public.tb_adm_roles (idnrole)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_adm_users_tb_adm_roles */
ALTER TABLE public.tb_adm_users ADD CONSTRAINT fk_tb_adm_users_tb_adm_roles
	FOREIGN KEY (idnrole) REFERENCES public.tb_adm_roles (idnrole)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_authorxproject_tb_prj_author */
ALTER TABLE public.tb_prj_authorxproject ADD CONSTRAINT fk_tb_prj_authorxproject_tb_prj_author
	FOREIGN KEY (idnauthor) REFERENCES public.tb_prj_author (idnauthor)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_authorxproject_tb_prj_projects */
ALTER TABLE public.tb_prj_authorxproject ADD CONSTRAINT fk_tb_prj_authorxproject_tb_prj_projects
	FOREIGN KEY (idnprj) REFERENCES public.tb_prj_projects (idnprj)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_documents_tb_prj_projects */
ALTER TABLE public.tb_prj_documents ADD CONSTRAINT fk_tb_prj_documents_tb_prj_projects
	FOREIGN KEY (idnprj) REFERENCES public.tb_prj_projects (idnprj)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_projectxlabel_tb_prj_projects */
ALTER TABLE public.tb_prj_projectxlabel ADD CONSTRAINT fk_tb_prj_projectxlabel_tb_prj_projects
	FOREIGN KEY (idnprj) REFERENCES public.tb_prj_projects (idnprj)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_projectxlabel_tb_prj_projects_labels */
ALTER TABLE public.tb_prj_projectxlabel ADD CONSTRAINT fk_tb_prj_projectxlabel_tb_prj_projects_labels
	FOREIGN KEY (idprjlabel) REFERENCES public.tb_prj_projects_labels (idprjlabel)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_typesxproject_tb_prj_projects */
ALTER TABLE public.tb_prj_typesxproject ADD CONSTRAINT fk_tb_prj_typesxproject_tb_prj_projects
	FOREIGN KEY (idnprj) REFERENCES public.tb_prj_projects (idnprj)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tb_prj_typesxproject_tb_prj_projects_types */
ALTER TABLE public.tb_prj_typesxproject ADD CONSTRAINT fk_tb_prj_typesxproject_tb_prj_projects_types
	FOREIGN KEY (idnprjtype) REFERENCES public.tb_prj_projects_types (idnprjtype)
	ON UPDATE NO ACTION ON DELETE NO ACTION;